### ISSUE TITLE
cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by canda** [AtomLinter/linter-sass-lint#105]
- Atom version:1.7.3
- linter-sass-lint version:1.6.1
- Global sass-lint version (if used):
- Platform:
  - [ ] OSX
  - [ ] Windows
  - [X] Linux: Ubuntu 14.04
- Expected behaviour:Lint
- Actual behaviour / issue description:Not linting
I paste a simple css rule like
```
.asd {
  height: auto;
}
```
And I get "cannot read property 'toString' of undefined"
When I delete everything I get "Cannot find module './node/empty-node' "

**Comment by DanPurdy** [comment]
Have you tried uninstalling and reinstalling. This is working fine for me. Also are you using the global sass-lint option or not?

**Comment by jackmcpickle** [comment]
Ok had the same issue - after I updated a rule. About an hour of mucking around with configs and reinstalling - to no avail. 

But solution came by looking in the dev tools console. `cmd + opt + i` to open OSX. A rule must have changed name of something. 

Your answer lays there.

**Comment by DanPurdy** [comment]
Can you post the error here maybe and your config file.

**Comment by DanPurdy** [comment]
Closing due to lack of information. This also looks like a sass-lint issue rather than linter-sass-lint.

**Comment by jackmcpickle** [comment]
Agreed. Unless you want to handle invalid config keys and display a better message?

In my case I was using the key `no-color-keyword: 1` which should be `no-color-keywords: 1`
this was causing the error.

**Comment by DanPurdy** [comment]
I'd rather handle it in sass-lint itself, this plugin doesn't actually care about any of the functionality of sass-lint it just consumes sass-lint.
