### ISSUE TITLE
Rule "function-name-format" doesn't work~

### ISSUE THREAD

**Issue by yalishizhude** [AtomLinter/linter-sass-lint#106]
- Atom version: 1.7.2
- linter-sass-lint version: 1.6.1
- Global sass-lint version (if used):
- Platform:
  - [ ] Windows
- Expected behaviour: camelcase function name should be allowed.
- Actual behaviour / issue description: the info shows:Function xxx should be written in lowercase with hyphens.

.sass-lint.yml
```
function-name-format:
    convention: 'camelcase'
```

.scss file
```
@function tomCat($x) {
  @return $x;
}
```

sass-lint info
`function-name-format Function 'tomCat' should be written in lowercase with hyphensat line 4 col 11`

**Comment by DanPurdy** [comment]
Hi @yalishizhude you need to report this with https://github.com/sasstools/sass-lint as this plugin only consumes it.

At first look though you might want to try validating your config with http://www.yamllint.com/ as it doesn't look valid.

**Comment by yalishizhude** [comment]
Thanks a lot~
