### ISSUE TITLE
Disable option not preventing sass-lint from linting files

### ISSUE THREAD

**Issue by andrewmartin** [AtomLinter/linter-sass-lint#108]
I'm working on a project where I need `sass-lint` to be disabled because the team is using `stylelint` instead. I'm having trouble getting it to disable. There is no `.sass-lint.yml` set in my project root.
- Atom version: 1.8.0
- linter-sass-lint version: 1.6.1
- Global sass-lint version (if used): N/A
- Platform:
  - [ X ] OSX
  - [ ] Windows
  - [ ] Linux
- Expected behaviour: 

Flagging the checkbox "Disable when no sass-lint config file is found in your project root" should disable linting:

![](http://cloud.believelabs.com/1p3Y0G1A2320/Image%202016-06-30%20at%2019.59.59.png)
- Actual behaviour / issue description:

sass-lint is still being triggered. Have tried restarting Atom, etc. to no avail.

**Comment by DanPurdy** [comment]
Thanks for the report, it's odd but I'll look into it!

**Comment by albell** [comment]
Confirmed still happening on 1.13.1 on MacOS.

I have taken the config out of the project completely, checked the "Disable when no sass-lint config file is found in your project root" checkbox in settings, restarted Atom, and I'm still getting linting errors when I open a `.scss` file.
