### ISSUE TITLE
Lint as you type

### ISSUE THREAD

**Issue by zslabs** [AtomLinter/linter-sass-lint#11]
Right now, this linter does not lint as I type; it only lints after a save. This is different than how most other Atom Linters work. I'm not seeing a setting for this behavior; is this intended? Thanks.

**Comment by Arcanemagus** [comment]
It's the way this linter is currently written at least. Does `sass-lint` support linting input from stdin?

**Comment by DanPurdy** [comment]
Hi @zslabs sorry I meant to reply here after closing your issue on the sass-lint repo. It is technically possible to do it but at the time I built this plugin originally `sass-lint` was fairly young and a little unstable. The AST we use also throws parse errors quite frequently which sass-lint currently isn't handling 'well' I've got a [PR](https://github.com/sasstools/sass-lint/pull/459) open to patch this a bit but we've all been a bit too busy recently to work on `sass-lint` hopefully that's going to change this month though...

**Comment by zslabs** [comment]
Appreciate the update @DanPurdy! Do prefer this to the other `scss-lint` lib for Atom and think this feature would be a great addition.
