### ISSUE TITLE
Error on `sass` import

### ISSUE THREAD

**Issue by mikeerickson** [AtomLinter/linter-sass-lint#135]
I am receiving an error when using .sass files (not .scss) and calling @import.  As you can see by the included screenshot, it is throwing a fatal error.

When using the `sass-lint` CLI, the following is required (see the -f option set as sass)

`$ sass-lint \"../ci-components/app/components/gmail-addin/*.sass\" -f sass -q -v`

- Atom version:   1.9.8
- linter-sass-lint version:  1.7.0
- Global sass-lint version (if used):  1.8.2
- Platform:
  - [x] OSX
  - [ ] Windows
  - [ ] Linux
- Expected behaviour: Dont show this as an error 
- Actual behaviour / issue description: See screen

<img width="641" alt="eslint-fatal-error" src="https://cloud.githubusercontent.com/assets/183153/17684228/baaac7c4-630e-11e6-9d6a-d7d7a70b06a2.png">

**Comment by DanPurdy** [comment]
This is a problem with the AST that sass-lint uses `Gonzales-pe` https://github.com/tonyganch/gonzales-pe you'll need to report the issue there, it looks like it's due to the lack of quotes around the import
