### ISSUE TITLE
Config file not actually updating config

### ISSUE THREAD

**Issue by youpiwaza** [AtomLinter/linter-sass-lint#148]
Hi there,

Not sure if this is a bug or not but adding and editing a .sass-lint.yml file at the root of the project doesn't seem to change anything.

The plugin actually detects it (I got a warning if there is no such file) but it doesn't take in account any modifications. I've tried to set 
NameFormat > convention > camel_case
// NameFormat > enabled > false
NestingDepth > max_depth > 7

Tried to update config through closing/re-openning .scss files, and also de-activate/re-activate plugin but it just lint with default config.
Edit: Also tried closing/re-openning Atom.

---
- Atom version: latest (23/09/16)
- linter-sass-lint version: latest (23/09/16)
- Global sass-lint version (if used): latest (23/09/16)
- Platform:
  - [ ] OSX
  - [X] Windows > Atom + cygwin
  - [ ] Linux
- Expected behaviour: config taken into account /:
- Actual behaviour / issue description: default config despite config file.

---

![capture-1](https://cloud.githubusercontent.com/assets/10812138/18783251/1f2477aa-818b-11e6-97aa-6480943a4f74.jpg)

![capture-2](https://cloud.githubusercontent.com/assets/10812138/18783260/2a573a72-818b-11e6-9b7a-1de1f5978518.jpg)

---

Thanks, and feel free to ask if you have any question

**Comment by albell** [comment]
+1. Confirming on MacOS. Local config in the root straight-up doesn't work. Linting from the CLI does. The user always seems to get the default. I can share my project if that's helpful.

**Comment by DanielTamkin** [comment]
+1. Confirming on Windows 10. Local config in the root doesn't work, CLI linting just as @albell.

**Comment by DanPurdy** [comment]
Sorry, I've not had the time to look into this. It's probably linked to the issue reported in #108 and i've started fixing in #116

Will update this when I can.

**Comment by JockVanDallas** [comment]
This is still a thing, changing sass-lint.yml config file does not change the way the linting is done. It will take all the presets. 
Using:
OSX
 atom 1.17.0
 linter 2.1.4
 linter-sass-lint 1.7.4

**Comment by DanPurdy** [comment]
Sorry for the delay this should be fixed now in v1.8.0 of linter-sass-lint. I've tried with the examples provided to me. If this continues to be an issue please create a new issue with a sample of your config file and a basic project structure to allow me to debug this a little further. Thanks!
