### ISSUE TITLE
Specify folder inside the project for config file

### ISSUE THREAD

**Issue by quicoto** [AtomLinter/linter-sass-lint#163]
Hello,

Is there any way for us to set a relative path for the sass-lint config file inside the project?

**Example**: instead of having  the file in the roof, I might want to have all my configuration in /config/sass-lint.yml

Is there a way to set this path /config/ so the plugin looks there too instead of the root folder only?

Thank you

---
- Atom version: 1.12.4
- linter-sass-lint version: 1.7.4
- Platform:
  - [X ] OSX

**Comment by DanPurdy** [comment]
You can specify a config file to directly reference already, but there's a bug I intend to finish fixing soon where your project isn't searched for a config file which would fix this automatically for you.

You can see #108 for the initial bug report and #116 for the fix i need to finish.
