### ISSUE TITLE
lint css files

### ISSUE THREAD

**Issue by abumalick** [AtomLinter/linter-sass-lint#165]
Hello,
Is it possible to lint css files with this plugin ?
Thanks

**Comment by DanPurdy** [comment]
Technically the AST that Sass-lint uses supports css but Sass-lint itself isn't designed to lint pure css files.

**Comment by CASandmann** [comment]
I don't understand.  CSS is a subset of Sass, isn't it?  When I change the configuration of the yml file to include *.css files as well (`files: include: 'app/**/*.?(s)@(a|c)ss'`) and I run `sass-lint`, I get the errors outputted to my console.  I don't see any errors in any css files in atom with this plugin, and that leads to a very poor user experience.
