### ISSUE TITLE
atom package not linting when file paths in .sass-lint.yml include `./`

### ISSUE THREAD

**Issue by patriciarealini** [AtomLinter/linter-sass-lint#168]
at the top of our .sass-lint.yml file we reference a couple files. when the references are written as follows, linter-sass-lint isn't working in atom.

```
files:
    include: './scss/**/*.scss'
    ignore: './node_modules/**/*.scss'
```

however when the references are listed without the `./` at the beginning of each file route, the linter works. 

```
files:
    include: 'scss/**/*.scss'
    ignore: 'node_modules/**/*.scss'
```

i would like to recommend that this requirement  be documented.

- Atom version: 1.15.0 x64
- linter-sass-lint version: 1.7.4
- Global sass-lint version (if used): 
- Platform:
  - [x] OSX
  - [ ] Windows
  - [ ] Linux
- Expected behavior: linting errors in atom
- Actual behavior / issue description: no linting errors in atom

**Comment by DanPurdy** [comment]
Hi there,

The config file is part of Sass-lint itself, it wont be documented in this repo as this package purely interfaces it.

If you don't think the docs for this [here](https://github.com/sasstools/sass-lint#files) are enough then I would suggest opening a issue on the main Sass-lint repo or even opening a pull request with your suggestion.

Thanks.

**Comment by noudadrichem** [comment]
Hahaha, what an easy fix. @patriciarealini thanks!
