### ISSUE TITLE
PropertySortOrder disabled is ignored

### ISSUE THREAD

**Issue by followalter** [AtomLinter/linter-sass-lint#171]
- Atom version: 1.16.0
- linter-sass-lint version: 1.7.4
- Global sass-lint version (if used):
- Platform:
  - [V] OSX
  - [ ] Windows
  - [ ] Linux
- Expected behaviour: Ignore PropertySortOrder
- Actual behaviour / issue description:
I have this in my .sass-lint.yml file:
  PropertySortOrder:
    enabled: false

But I still get these warnings:
Warning	sass-lint	property-sort-order Expected `color`, found `height`

Seems like disabling sort order is not working?

Best,
Tom

**Comment by Arcanemagus** [comment]
Does `sass-lint` show the expected results from the CLI?
