### ISSUE TITLE
[Linter] Error running scss-lint

### ISSUE THREAD

**Issue by MajorTom250993** [AtomLinter/linter-sass-lint#177]
# Issue Description

Version: linter-scss-lint 3.1.0
![captura de pantalla 2017-06-26 a la s 22 50 35](https://user-images.githubusercontent.com/21065249/27570244-488fd8d0-5ac2-11e7-877a-3b5ca03d75ca.png)

I don't know what to do.

**Comment by richarddewit** [comment]
That's a whole different package:

    Yours: linter-s**c**ss-lint
    This:  linter-s**a**ss-lint

Also
> I don't know what to do.

Read the error popup.. 

> See Console for more info. (Open View -> Developer -> Toggle Developer Tools)

**Comment by Arcanemagus** [comment]
Closing, if you are still having problems @MajorTom250993 please file that on the [right repo](https://github.com/AtomLinter/linter-scss-lint/issues).

**Comment by flurdulis** [comment]
I have the same issue. I went ahead and opened Toggle Developer Tools. The console states this error:

**[Linter] Error running scss-lint Error: Failed to spawn command `scss-lint`. Make sure `scss-lint` is installed and on your PATH.** 

I have installed linter-scss-lint via Atom. How suddenly it is not in my path? And how to fix it?

Thanks,
Elle

**Comment by flurdulis** [comment]
Okay, the global install of scss_lint ruby gem fixed the issue of not finding the path.
