### ISSUE TITLE
Background URL linting crashing editor

### ISSUE THREAD

**Issue by brainbrian** [AtomLinter/linter-sass-lint#184]
## Crashing when configuring background image urls
When adding `background: url()` or `background-image: url()` it crashes atom.

- Atom version: 1.20.0 x64
- linter-sass-lint version: 1.7.6
- Global sass-lint version (if used): 1.10.2
- Platform: OSX 10.12.6
- Expected behaviour: Lints file correctly and allows user to complete the background url declaration.
- Actual behaviour / issue description: Freezes and crashes current Atom project.

**Comment by Arcanemagus** [comment]
Does `sass-lint` freeze when running on that file in the CLI? That's a somewhat old version of `sass-lint` and I believe @DanPurdy said that several infinite loop issues were fixed in the parser upgrade in `sass-lint` v1.11.0.

**Comment by DanPurdy** [comment]
Seems you might of found a new one though @brainbrian I've opened an issue and we'll look into it there https://github.com/tonyganch/gonzales-pe/issues/282.

WIll close this issue as it's AST related not the atom plugin.

Thanks!
