### ISSUE TITLE
What is the command to run this in the terminal?

### ISSUE THREAD

**Issue by leon-yum** [AtomLinter/linter-sass-lint#196]
Expected this to work

`npm run scss-lint'

**Comment by leon-yum** [comment]
Figured it out
`"test-scsslint": "./node_modules/.bin/sass-lint 'client/styles/**/*.scss' -v -q",`

**Comment by Arcanemagus** [comment]
A couple of things here:
* The [CLI](https://github.com/sasstools/sass-lint#cli) section of the `sass-lint` README would have explained this for you, this is the `linter-sass-lint` repo which is a wrapper around that 😉.
* You can just use `sass-lint ....` in your `scripts`. `npm` will automatically use the project local bin for you.

**Comment by DanPurdy** [comment]
You're also mixing up scss-lint and sass-lint there, be careful as they're 2 different packages
