### ISSUE TITLE
Style lint issue

### ISSUE THREAD

**Issue by ChristopherNowlan** [AtomLinter/linter-sass-lint#22]
Error: Parsing error at /Users/christophernowlan/Documents/Folio:SelfBranding/website/build/assets/scss/config/_variables.scss: Please check validity of the block starting from line #196 at module.exports (/Users/christophernowlan/.atom/packages/linter-sass-lint/node_modules/sass-lint/lib/groot.js:21:11) at Function.sassLint.lintText (/Users/christophernowlan/.atom/packages/linter-sass-lint/node_modules/sass-lint/index.js:36:13) at Object.provider.lint (/Users/christophernowlan/.atom/packages/linter-sass-lint/lib/main.coffee:136:29) at promises.push.Promise.then._this.emitter.emit.linter (/Users/christophernowlan/.atom/packages/linter/lib/linter-registry.js:63:26) at /Users/christophernowlan/.atom/packages/linter/lib/linter-registry.js:62:23 at Set.forEach (native) at LinterRegistry.lint (/Users/christophernowlan/.atom/packages/linter/lib/linter-registry.js:60:18) at /Users/christophernowlan/.atom/packages/linter/lib/linter.coffee:98:16 at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11) at /Users/christophernowlan/.atom/packages/linter/lib/editor-linter.js:80:22 at /Users/christophernowlan/.atom/packages/linter/lib/helpers.coffee:23:18

**Comment by Arcanemagus** [comment]
This looks like an issue with `sass-lint` itself, do you see the same stack when you run that from the terminal?

**Comment by DanPurdy** [comment]
Hey @ChristopherNowlan can you check what version of `linter-sass-lint` you're running, these parse errors are indeed created by the AST that sass-lint is using BUT the latest version of this plugin should be registering them as lint errors rather than full blown errors as you can see here

<img width="461" alt="screen shot 2016-01-25 at 23 24 32" src="https://cloud.githubusercontent.com/assets/1386054/12568054/decf79cc-c3ba-11e5-9cb2-d69091cc5efa.png">

There are a few reasons the AST throws parse errors so it would also be helpful if you could post the code that it's failing on and i'd be able to point you in the direction of why.. Normally it's because you've got some invalid Sass/scss somewhere but it can also be from things like interpolation (which the AST doesn't like at the moment)

When i get round to releasing 1.5.0 of `sass-lint` these parse errors will stop throwing unhandled errors anyway.

**Comment by ChristopherNowlan** [comment]
Hey @DanPurdy I am using v1.0.2. I am using it with Atom. I do think it is some invalid sass/scss as well.

**Comment by ChristopherNowlan** [comment]
// Container widths
// ==============================================
* {
  box-sizing: border-box;
  &:before,
  &:after {
    box-sizing: border-box;
  }
}
// Set the container width, and override it for fixed navbars in media queries.
// ==============================================
.container {
  @include make-container();
  // For each breakpoint, define the maximum width of the container in a media query
  @each $breakpoint,
  $container-max-width in $container-max-widths {
    @include media-breakpoint-up($breakpoint) {
      max-width: $container-max-width;
    }
  }
}
// Fluid container - Utilizes the mixin meant for fixed width containers, but without any defined width for fluid, full width layouts.
// ==============================================
.container-fluid {
  @include make-container();
}
// Row - Rows contain and clear the floats of your columns.
// ==============================================
.row {
  @include make-row();
}
// Columns - Common styles for small and large grid columns
// ==============================================
@include make-grid-columns();
//Flex variation */
// ==============================================
//Custom styles for additional flex alignment options. */
@if $enable-flex {
  // Flex column reordering
  .col-xs-first {
    order: -1;
  }
  .col-xs-last {
    order: 1;
  }
  @include media-breakpoint-up(sm) {
    .col-sm-first {
      order: -1;
    }
    .col-sm-last {
      order: 1;
    }
  }
  @include media-breakpoint-up(md) {
    .col-md-first {
      order: -1;
    }
    .col-md-last {
      order: 1;
    }
  }
  @include media-breakpoint-up(lg) {
    .col-lg-first {
      order: -1;
    }
    .col-lg-last {
      order: 1;
    }
  }
  @include media-breakpoint-up(xl) {
    .col-xl-first {
      order: -1;
    }
    .col-xl-last {
      order: 1;
    }
  }
  // Alignment for every column in row
  .row-xs-top {
    align-items: flex-start;
  }
  .row-xs-center {
    align-items: center;
  }
  .row-xs-bottom {
    align-items: flex-end;
  }
  @include media-breakpoint-up(sm) {
    .row-sm-top {
      align-items: flex-start;
    }
    .row-sm-center {
      align-items: center;
    }
    .row-sm-bottom {
      align-items: flex-end;
    }
  }
  @include media-breakpoint-up(md) {
    .row-md-top {
      align-items: flex-start;
    }
    .row-md-center {
      align-items: center;
    }
    .row-md-bottom {
      align-items: flex-end;
    }
  }
  @include media-breakpoint-up(lg) {
    .row-lg-top {
      align-items: flex-start;
    }
    .row-lg-center {
      align-items: center;
    }
    .row-lg-bottom {
      align-items: flex-end;
    }
  }
  @include media-breakpoint-up(xl) {
    .row-xl-top {
      align-items: flex-start;
    }
    .row-xl-center {
      align-items: center;
    }
    .row-xl-bottom {
      align-items: flex-end;
    }
  }
  // Alignment per column
  .col-xs-top {
    align-self: flex-start;
  }
  .col-xs-center {
    align-self: center;
  }
  .col-xs-bottom {
    align-self: flex-end;
  }
  @include media-breakpoint-up(sm) {
    .col-sm-top {
      align-self: flex-start;
    }
    .col-sm-center {
      align-self: center;
    }
    .col-sm-bottom {
      align-self: flex-end;
    }
  }
  @include media-breakpoint-up(md) {
    .col-md-top {
      align-self: flex-start;
    }
    .col-md-center {
      align-self: center;
    }
    .col-md-bottom {
      align-self: flex-end;
    }
  }
  @include media-breakpoint-up(lg) {
    .col-lg-top {
      align-self: flex-start;
    }
    .col-lg-center {
      align-self: center;
    }
    .col-lg-bottom {
      align-self: flex-end;
    }
  }
  @include media-breakpoint-up(xl) {
    .col-xl-top {
      align-self: flex-start;
    }
    .col-xl-center {
      align-self: center;
    }
    .col-xl-bottom {
      align-self: flex-end;
    }
  }
}

**Comment by DanPurdy** [comment]
Hmm, that parses fine for me..

<img width="1533" alt="screen shot 2016-01-26 at 08 10 31" src="https://cloud.githubusercontent.com/assets/1386054/12575438/5fb62a92-c404-11e5-86a0-1a64d29a2332.png">

Are you using hard tabs? The AST sometimes chokes on tabs too as ridiculous as that sounds. Other than that the only thing i can think about is that you're using an old globally installed version of sass-lint?

**Comment by DanPurdy** [comment]
I think this may be related to the change in #23 after all I just witnessed it first hand. Update will be out soon

**Comment by DanPurdy** [comment]
I'm going to close this as it's definitely an issue with sass-lint itself. I've removed the annoying pop up errors for now and transformed to lint errors, I'll be improving this soon though.
