### ISSUE TITLE
Version 1.0.0 and higher doesn't work

### ISSUE THREAD

**Issue by hellobrian** [AtomLinter/linter-sass-lint#24]
Since updating to version 1.0.0 and higher of `linter-sass-lint`, atom doesn't seem to fir off any notifications when I break rules declared in my `.sass-lint.yml`

So I reverted back to using `linter-sass-lint@0.6.3`

```
apm list

/Users/brianhan/.atom/packages (16)
...
├── linter@1.11.3
├── linter-sass-lint@0.6.3
...
```

I also made sure that I'm including the correct paths to my scss files.
Here's a gist of my [`.sass-lint.yml`](https://gist.github.com/hellobrian/ea3a65e8dd3ce8dbd0b4) for reference.

Please let me know if there's anything I can do to help make this issue easier to resolve.

Thanks!

**Comment by DanPurdy** [comment]
It definitely does work! :smile:

Have you configured the new options that are included? Is your .sass-lint.yml in the root of your open project?

The readme has details on how they should work. The option to use a specified version of sass-lint has gone too in favour of it using just the global sass-lint you have installed or the version included with this package.

**Comment by hellobrian** [comment]
Yes, `.sass-lint.yml` is located in the root of my project. 

My project structure looks like this where each scss directory includes multiple sub-folders of scss files.
```
.
├── base-elements (scss directory)
├── components (scss directory)
├── dev-colors.scss
├── dev-typography.scss
├── global (scss directory)
├── .sass-lint.yml
└── styles.scss
```

I'm reading through the [Settings section in README.md](https://github.com/AtomLinter/linter-sass-lint#settings). And it didn't seem like I needed to update my `~/.atom/config.cson` with any of the new settings.
I'd like to only use a `.sass-lint.yml` in the root of my project directory and let atom notify me when I break the rules set in my project's `.sass-lint.yml`.

**Comment by DanPurdy** [comment]
Ok, so it's probably the fact that i managed to fix an issue with sass-lint itself recently. Can you post the files section of your `.sass-lint.yml` you'll probably find that your files aren't covered by the 'include' section. The include paths should be relative to your project. If it's not already try changing include to just '**/*.scss and check you're not ignoring any files inadvertently.

**Comment by hellobrian** [comment]
Thanks for all the help, I tried changing include to `**/*.scss` and that worked.
Will update my files section accordingly :+1:

**Comment by DanPurdy** [comment]
No problem, as i said probably my fault for not originally respecting these settings. All sorted now though :smile:
