### ISSUE TITLE
Custom config is being ignored if no config is present in root

### ISSUE THREAD

**Issue by DanPurdy** [AtomLinter/linter-sass-lint#25]
It seems the logic to check if a config exists is the wrong way around.

If a config file isn't present in your root and you have one specified in the settings, the config in your settings should be used instead before it is ignored completely

**Comment by Arcanemagus** [comment]
Just curious, what's the `developer experience` tag for?

**Comment by DanPurdy** [comment]
It's basically a user experience issue, users being developers :smile: it's not a critical flaw basically just a nicety i think.

**Comment by Arcanemagus** [comment]
Ah ha, makes sense.

**Comment by DanPurdy** [comment]
Though being a linter plugin you could probably argue that all bugs are of this nature!

**Comment by DanPurdy** [comment]
This is actually invalid and not a bug at all. Turns out the included files glob was incorrect.
