### ISSUE TITLE
Atom freezes when removing character after 'dollar sign'

### ISSUE THREAD

**Issue by Damon-E** [AtomLinter/linter-sass-lint#27]
e.x.    "@include breakpoint(**$tab2**)"

While backspacing from '2' to '$' it crashes when it reaches the '$'

**Comment by DanPurdy** [comment]
That's really strange... I've managed to recreate it too it's only if you leave the $ on it's own in the brackets and if you dont have a semicolon following it!

I shall investigate, thanks for the report @Damon-E :+1:

**Comment by mdmoreau** [comment]
Just ran into this same issue when editing a media query mixin.  It crashes every time I enter a `$` anywhere inside the mixin definition.

**Comment by DanPurdy** [comment]
So over at sass lint we're extremely close to our update to the newest version of the AST we use, I'm not entirely sure this is linked to that but it will certainly provide a more stable base from which to debug this a bit.

**Comment by DanPurdy** [comment]
Ok so this is actually fixed now but I'll re open #98 as it's still relevant for keyframes until they're fixed in gonzales-pe the AST sass-lint uses.
