### ISSUE TITLE
Atom craches on save

### ISSUE THREAD

**Issue by pawelgrzybek** [AtomLinter/linter-sass-lint#3]
Hello.

Version of Atom: 1.3.2
linter-sass-lint version: 0.5.0

My settings
```
"linter-sass-lint":
    configPath: "~/.sass-lint.yml"
    executablePath: "/usr/local/bin/sass-lint"
```

Basically I try to use use globally installed version of sass-lint and global dotfile with settings.

Editor crashes on save. When plugin is disabled Atom saves files with no issue. Linter doesnt work before saving attempt. Any ideas, any updates expected?

**Comment by pawelgrzybek** [comment]
Passing executablePath causes crash. configPath works fine.

**Comment by Arcanemagus** [comment]
Looks like unlike other linters this uses `executablePath` as the path to the folder where `sass-lint` is installed (the `node_modules\sass-lint` folder), can you try putting that in there?

**Comment by steelbrain** [comment]
A README clarification for this would be nice

**Comment by DanPurdy** [comment]
The plugin pulls down the latest version of sass-lint as a dependency when you install it so the executable path is only needed if you want to use an older version or custom version of sass-lint itself. I imagined it would be a way to prevent the issues people have with installing other dependencies for linter plugins but maybe not! :stuck_out_tongue: 

I'll update the README and the field description itself and give this a test too.

**Comment by DanPurdy** [comment]
Also be careful not to point it to an alias of your globally installed package, that it seems will most definitely crash it.

I don't interface with sass-lints CLI here I am directly calling methods there, maybe I should rename `executable-path` to something else as orignally it was the CLI and it's just not had a name update I guess.

**Comment by Arcanemagus** [comment]
@DanPurdy you might check out how linter-eslint handles it since it is in a similar situation. It's a mess though handling using custom ones properly.

**Comment by pawelgrzybek** [comment]
Maybe consider and option (checkbox) like 'Use globally installed sass-lint'. Thanks for all advices and keep on doing good work man! I like your plugin, helps a lot!

**Comment by DanPurdy** [comment]
I'm sort of leaning that way, the main reason it's there is sort of a selfish one as it's easier for me to debug unreleased sass-lint versions directly in atom rather than trawling through AST trees by other means. Though `npm-link` will solve that for me so I'll possibly add it to the next version.

**Comment by pawelgrzybek** [comment]
That would be awesome :) Thanks!
