### ISSUE TITLE
Project .sass-lint.yml not being detected.

### ISSUE THREAD

**Issue by jessejanderson** [AtomLinter/linter-sass-lint#31]
If I manually specify the file in Settings "Config File" path it works, otherwise I get errors that no config file is found.

**Comment by DanPurdy** [comment]
Do you have it in the root of your project?

**Comment by jessejanderson** [comment]
Yah.

`~/Code/Project/.sass-lint.yml`

**Comment by DanPurdy** [comment]
That's odd then, would you mind giving me a printout of your project structure?

**Comment by jessejanderson** [comment]
Not sure what you're asking? It's a rails app with my .sass-lint.yml in the project root.

**Comment by DanPurdy** [comment]
Sorry @jessejanderson, do you get any errors popping up about the config missing or is it just not linting anything?

**Comment by DanPurdy** [comment]
Im not really sure how to get to the bottom of this im afraid, all of my tests are passing fine and I can't get a config not to be detected.. Do you use Winows/linux/osx?

**Comment by DanPurdy** [comment]
I'm going to close this as i really can't reproduce this issue. Feel free to open again if the issue persists.

**Comment by TolgaND** [comment]
Having the exact same problem here. I am using Max OS X and atom can't find .sass-lint.yml 
![screen shot 2016-09-21 at 13 21 35](https://cloud.githubusercontent.com/assets/7658320/18709063/6fbcf98c-7ffe-11e6-9f46-5f5b61e1c2dc.png)

**Comment by siberianbear** [comment]
Same issue for me.

**Comment by bjornwang** [comment]
Same issue here. Mac OS X.

**Comment by nmfzone** [comment]
+1 Same issue here. Mac OS X El Capitan. Atom version 1.13.0.

**Comment by piotrkulpinski** [comment]
I think you guys should be using this one: https://atom.io/packages/linter-scss-lint

**Comment by pascalhuynh** [comment]
Same issue here. Mac OS X with Atom 1.14.1

**Comment by pedromsduarte** [comment]
Same issue here. OS 10.11.6 Atom 1.14.4

**Comment by odyright** [comment]
Same issue here. OS 10.12.4 Atom 1.17.0

**Comment by odyright** [comment]
i solved it, solution:
![capture d ecran 2017-05-19 a 10 41 52](https://cloud.githubusercontent.com/assets/4316506/26244684/4ace30de-3c80-11e7-8c93-f8ee131d2ea5.png)

**Comment by k-utsumi** [comment]
In my case, it worked after unchecking `Use global sass-lint installation`.
![settings](https://cloud.githubusercontent.com/assets/13148112/26616191/b8333116-4607-11e7-9fb7-6420d288fd74.png)

**Comment by mrleblanc101** [comment]
Same problem.
Used @odyright solution.
Atom 1.24.0
macOS 10.13.4
