### ISSUE TITLE
Update dependencies recently locked down

### ISSUE THREAD

**Issue by DanPurdy** [AtomLinter/linter-sass-lint#33]
`consistent-path` and `atom-package-deps` have had their versions locked down here to prevent tests failing before i have time to investigate. They will need to be updated to the latest versions again manually.

**Comment by Arcanemagus** [comment]
`atom-package-deps@3.0.9` depends on a fixed version of the sub-dependency that was broken when v3.0.8 first came out.

**Comment by Arcanemagus** [comment]
Looks like `consistent-path` was a similar issue, need to get deployment from CI working for those so things can't get out without a proper package :frowning:.

**Comment by DanPurdy** [comment]
Thanks @Arcanemagus I'm looking into it. I cannot get the tests to pass locally at all and whenever you run them again on CI they fail. Im not entirely sure why the tests have become so flaky all of a sudden..

**Comment by DanPurdy** [comment]
And then they pass again.. :/

**Comment by Arcanemagus** [comment]
Not sure what was going on on your local install, the CI builds were probably due to the caching those services try to do.

**Comment by DanPurdy** [comment]
I've updated #35 with some findings, it looks like the wrong path is getting set. The travis build for this also never passes.

**Comment by DanPurdy** [comment]
closed with #50
