### ISSUE TITLE
Fatal errors when linting Jekyll main.scss files

### ISSUE THREAD

**Issue by tohuw** [AtomLinter/linter-sass-lint#37]
For the "main.scss" file used in Jekyll, it must have front matter markings, e.g.:

    ---
    # Only the main Sass file needs front matter (the dashes are enough)
    ---

However, this causes the linter to fatally error. Understandable: it's not valid SCSS. Unavoidable: Jekyll demands that front matter for proper compilation.

Proposal: add a config option to skip parsing the first *x* lines? Or does something like this already exist?

**Comment by DanPurdy** [comment]
This is something that we'd have to handle in sass-lint itself I'm afraid, it wouldn't be realistic to have this plugin start manipulating what it sends to the linter. 

More than likely we'd have to ask for the AST we use to accept this which I'm not sure would be feasible. It wouldn't hurt to make an issue with us over at [sass-lint](https://github.com/sasstools/sass-lint) though..
