### ISSUE TITLE
Updating to “linter-sass-lint@1.1.1” failed

### ISSUE THREAD

**Issue by warpcode** [AtomLinter/linter-sass-lint#51]
Received the below error when trying to update. Trying to upgrade from 1.0.5

npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/warpcode/.atom/.apm/.apmrc" "--userconfig" "/Users/warpcode/.atom/.apmrc" "install" "/private/var/folders/lh/j4l80yqs1s1b0tpzk6sn5wtw0000gn/T/d-116126-99137-16nukc0/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: lodash.upperfirst@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["4.0.0","4.0.1","4.0.2","4.1.0","4.1.1","4.1.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'lodash.capitalize'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/lh/j4l80yqs1s1b0tpzk6sn5wtw0000gn/T/apm-install-dir-116126-99137-69zfjh/npm-debug.log

**Comment by DanPurdy** [comment]
Have you tried uninstalling an reinstalling. It's probably just atoms dependency management failing again..

**Comment by warpcode** [comment]
Just tried and got pretty much the same error

Installing “linter-sass-lint@1.1.1” failed.Hide output…

npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/warpcode/.atom/.apm/.apmrc" "--userconfig" "/Users/warpcode/.atom/.apmrc" "install" "/private/var/folders/lh/j4l80yqs1s1b0tpzk6sn5wtw0000gn/T/d-116126-99225-1gl5645/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: lodash.upperfirst@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["4.0.0","4.0.1","4.0.2","4.1.0","4.1.1","4.1.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'lodash.capitalize'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/lh/j4l80yqs1s1b0tpzk6sn5wtw0000gn/T/apm-install-dir-116126-99225-t1mhnq/npm-debug.log

**Comment by DanPurdy** [comment]
Ok, same issue with sass-lint itself at moment.. Let me just look into it

**Comment by DanPurdy** [comment]
Hi @warpcode I've mentioned in https://github.com/sasstools/sass-lint/issues/549

Basically lodash have unpublished a lot of previous versions from npm which a LOT of packages are relying on. Hopefully they sort it soon

https://github.com/lodash/lodash/issues/2059

**Comment by warpcode** [comment]
Great. Thanks for the quick responses :)

**Comment by DanPurdy** [comment]
Hi @warpcode try reinstalling again now. We hotifxed sass-lint to get around the issue.

**Comment by DanPurdy** [comment]
Confirmed working here so i'll close this.
