### ISSUE TITLE
Warning about final-newline although present

### ISSUE THREAD

**Issue by nuflowx** [AtomLinter/linter-sass-lint#61]
- Atom version: 1.5.4
- linter-sass-lint version: 1.2.0
- Global sass-lint version (if used):
- Platform:
  - [x ] OSX
  - [ ] Windows
  - [ ] Linux
- Expected behaviour: No issue as final new line is automatically set by atom (or manually)
- Actual behaviour / issue description: Warning about the missing new line

I am using the "SASS"-syntax. When using "SCSS"-syntax this error does not occur.

![new-line-lint](https://cloud.githubusercontent.com/assets/17532211/14059747/bf4de746-f344-11e5-913e-581b92e8aa3e.png)

**Comment by nuflowx** [comment]
In general it seems to me that the lint is not working well for the "SASS"-syntax. Maybe I am doing something wrong, but I am seeing a lot of warnings which I know are valid writing.

These just don't make sense to me: :confused: 

![lint-warning-1](https://cloud.githubusercontent.com/assets/17532211/14059770/c97816be-f345-11e5-9960-175d512bd630.png)
![lint-warning-2](https://cloud.githubusercontent.com/assets/17532211/14059771/cd5d7f6c-f345-11e5-9d65-cc41cc9925dd.png)
![lint-warning-3](https://cloud.githubusercontent.com/assets/17532211/14059772/cf7b5d28-f345-11e5-98b7-e6b8625892c6.png)

**Comment by DanPurdy** [comment]
You need to report this over at the sass-lint repo I'm afraid. It's not an issue with this linter plugin.

Issues [here](https://github.com/sasstools/sass-lint/issues)

And in general yes, there's a lot of inconsistencies with the current version of the AST that sass-lint uses.

**Comment by nuflowx** [comment]
thanks for the quick response :+1: will do
