### ISSUE TITLE
`Unexpected parse error in file` when using 'Tab' indentation

### ISSUE THREAD

**Issue by RichardSlater** [AtomLinter/linter-sass-lint#70]
- Atom version: 1.7.0-beta5
- linter-sass-lint version: 1.3.1
- Platform:
  - [X] OSX
  - [X] Windows
  - [X] Linux
- Expected behaviour: valid SCSS generates no warnings even when tabs used for indentation
- Actual behaviour / issue description: when using tab characters instead of space characters for indentation in SCSS files the underlying `sass-lint` package throws a parser error: `Unexpected parse error in file`

![Screenshot](http://i.stack.imgur.com/sSL9L.png)

This issue is to track the following issues on [sasstools/sass-lint](https://github.com/sasstools/sass-lint) and was originally raised on [StackOverflow](http://stackoverflow.com/questions/36560486/sass-lint-in-atom-throws-unexpected-parse-error/36569606):

 - sasstools/sass-lint#62: Errors on files with tabs
 - sasstools/sass-lint#592: Allow tab indentation
 - sasstools/sass-lint#560: Nested element in element#id selector gives parse error.
 - ... and potentially any other [tab related issues with sass-lint](https://github.com/sasstools/sass-lint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+tab)

All of these seem to stem from a known issue (possibly with `gonzales-pe` - however I cannot find an associated defect!) when tabs are used for indentation rather than spaces.  It looks like the goal is to fix this for the 1.6 release, linter-sass-lint is currently using 1.5.

**Comment by RichardSlater** [comment]
Update on one from Dan Purdy on one of those linked issues:

> We're at a bit of a crossroads at the moment, while running through our tests on all platforms we've found the latest version of the AST fixes a lot of our issues but also breaks a few things. Specifically Sass format on windows mainly. There's also some pretty annoying windows bugs left over so we're currently debating and looking into what our best course of action is. I hope to have 1.6 out soon though... I just can't say when.

**Comment by DanPurdy** [comment]
I'm going to close this because it's an issue with sass-lint itself and there's already open issues over there that describe the problem. Thanks

**Comment by RichardSlater** [comment]
Thanks @DanPurdy, it's possibly a lack of clarity of my part as to how npm and Atom handle npm dependencies, does ^1.5.0 mean that 1.6 will be used when it is released?

Will that mean everyone will need to call `Update Package Dependencies: Update` to get the 1.6 update of the underlying sass-lint package or will it be offered as a pending update in the bottom right hand corner?

**Comment by Arcanemagus** [comment]
That does mean that 1.6 would be installed for new users (or people re-installing) on release, or if that command is called.

**Comment by DanPurdy** [comment]
@RichardSlater Dont worry, APM dependencies are a bit of a crazy thing anyway. So yeah If you reinstall this plugin once sass-lint 1.6 is out then it'll give you that latest version with the current version range specified in the package.json as @Arcanemagus mentioned. My plan though is once 1.6 is out I will bump the version in the package anyway to give people an easy path to update as im sure most users wont be regularly checking on sass-lint itself.

As for sass-lint, being one of the core developers I can't honestly say when 1.6 will be out, we need to spend some time fully understanding the consequences of the AST update we will be releasing with, unfortunately time is not something we have a lot of at the moment. It does solve a lot of issues but opens up some others :cry: 

If you want to use our latest develop branch with this plugin then you can clone `sass-lint` install all of its dependencies and then run npm link from the root of the project., this will symlink the repo to your global packages. You can then set `linter-sass-lint` to use your global version of sass-lint from the settings page. I use this to test things usually but I can't guarantee it will work for you right now and wont be able to offer support for it i'm afraid.

**Comment by aft3rlife** [comment]
I'm still getting this with the latest version of linter-sass-lint (1.7.0) using sass-lint 1.8.0.

I'm using the Sass syntax with spaces if that makes any difference.

**Comment by DanPurdy** [comment]
@aft3rlife please post this in the sass-lint repo itself with as much info as possible.. This plugin doesn't deal with these issues
