### ISSUE TITLE
Tool to indent

### ISSUE THREAD

**Issue by cristian-sima** [AtomLinter/linter-sass-lint#80]
This tool is doing a great job when it comes to checking the order of properties.

Is there any way to order these properties alphabetically?

It may be a very nice feature

**Comment by DanPurdy** [comment]
Hi there @cristian-sima 

This plugin is just an interface to our sass-lint project [see here](https://github.com/sasstools/sass-lint)

Have a look over at that repository as it explains how to set all of your options and rules up correctly and to your liking. If you haven't configured a config file yourself for your project yet then you will currently be using the default rules that sass-lint ships with which is fine but you can configure these however you like 👍 

If you have any issues with it then post an issue on sass-lint and we can help you out.

So in essence all that this atom plugin does is communicate between atom linter and sass-lint and as such doesn't do any of the linting itself that's sass-lints job 😄

**Comment by DanPurdy** [comment]
Oh and also the property sort order documentation is here https://github.com/sasstools/sass-lint/blob/develop/docs/rules/property-sort-order.md
