### ISSUE TITLE
Problem with BASH

### ISSUE THREAD

**Issue by cortopy** [AtomLinter/linter-sass-lint#84]
### Issue checklist
- Atom version: 1.7.3
- linter-sass-lint version: 1.4.2
- Global sass-lint version (if used): 0.48.0
- Platform:
  - [ ] OSX
  - [ ] Windows
  - [x ] Linux
- Expected behaviour:
Work without errors
- Actual behaviour / issue description:

When saving or opening a scss file I get the following error. Oddly, this doesn't happen with sass files:

```
Error: /usr/bin/bash: module: line 1: syntax error: unexpected end of file /usr/bin/bash: error importing function definition for BASH_FUNC_module' /usr/bin/bash: scl: line 1: syntax error: unexpected end of file /usr/bin/bash: error importing function definition forBASH_FUNC_scl'
```

The scss-lint command tool works fine with both scss and sass

**Comment by DanPurdy** [comment]
I think you've got `sass-lint` and `scss-lint` confused here.

linter-sass-lint is for `sass-lint` which is an all node linter [here](https://github.com/sasstools/sass-lint)
linter-scss-lint is for `scss-lint` which is a Ruby based linter [here](https://github.com/brigade/scss-lint)

So i would assume you're trying to point the linter-sass-lint global option towards the global ruby version here which won't work.

**Comment by cortopy** [comment]
@DanPurdy That certainly helps. I was just setting Atom up in a new computer and I got them mixed up.

**Comment by DanPurdy** [comment]
No problem 👍
