### ISSUE TITLE
Attempting to Include Files with Multiple .Exts Causes Error

### ISSUE THREAD

**Issue by tohuw** [AtomLinter/linter-sass-lint#90]
I tried the following in my `sass-lint.yml`:

    include:
      - '**/*.s+(a|c)ss'
      - '**/*.s+(a|c)ss.liquid'

The goal is to include files ending in `.sass`, `.scss`, or either with the additional extension `.liquid`.

This works for the first two cases, but any file ending in `.liquid` causes sass-lint to throw:
    Cannot read property 'toString' of undefined

- Atom version: 1.7.3
- linter-sass-lint version: 1.4.3
- Global sass-lint version (if used):
- Platform: OS X

**Comment by DanPurdy** [comment]
This is currently a combination of a few things firstly SassLint reads the file extension and passes it through to the AST which in this case would be `.liquid` the AST we use then doesn't know how to interpret this so it throws this error.

I'll have a look at what I can do but this isn't an issue with this plugin as it's just a bridge between atom linter and SassLint itself. I'll leave this open as a reminder for me though. Thanks for the report 👍

**Comment by tohuw** [comment]
I can't get sass-lint itself to work on my system for some reason, or I'd have tested it to see if it replicates there. If you can confirm it's upstream, I'm happy to report it there. I'll wait until your investigation as it undoubtedly will yield more fruit than my blind spelunking might.

**Comment by DanPurdy** [comment]
It's ok, I'm one of the core developers for sass-lint too so i'll have a poke around again. It is actually something that could be sorted in this plugin on second thoughts.

This line is the issue https://github.com/AtomLinter/linter-sass-lint/blob/master/lib/main.coffee#L139 it's just blindly sending the extension through without checking for a matching `sass` or `scss` format. 

Should be an easy fix, will look into it when i get a chance unless you want to put a PR in here?

Happy either way.

**Comment by DanPurdy** [comment]
My next question is how are you even getting these files noticed by linter-sass-lint? 

By default it's only looking at the following grammars '.scss', '.sass', '.css.scss', '.css.sass' I've never used the liquid shopify stuff so i'm not sure what steps you've taken here. For me it wont even attempt to lint the files.

**Comment by DanPurdy** [comment]
@tohuw This should be sorted in linter-sass-lint v1.5.0. Let me know if you have any problems with it.
