### ISSUE TITLE
Add an option for resolving paths relative to configuration file instead of project root

### ISSUE THREAD

**Issue by DirtyHairy** [AtomLinter/linter-sass-lint#99]
We are working on a large project where the directory containing the sass sources and the `.sass-lint.yml` config reside in a subfolder in the project workspace. In this setup, the linter fails to pickup the sass sources because the path globs in the config are evaluated relative to the project root. It would be nice to have an option to resolve the paths relative to the config file instead (as is done by the underlying `sass-lint` package itself).

**Comment by DirtyHairy** [comment]
See #100

**Comment by DanPurdy** [comment]
closed via #101
